### ISSUE TITLE
[Q] do you handle data persistance ?

### ISSUE THREAD

**Issue by ka2er** [ahmet2mir/dockerfiles#1]
if you re-create a docker instance of Shaarli did you have a way to persist data beetwen old and new one ?

**Comment by ahmet2mir** [comment]
Backup the old data folder and just "mount" it in the container:

```
 docker run -d -v /mydatabackupedfolder:/var/www/data ahmet2mir/shaarli
```

**Comment by ka2er** [comment]
thanks that does the trick
