### ISSUE TITLE
geminabox: restricted access to the home page

### ISSUE THREAD

**Issue by yuri-karpovich** [ahmet2mir/dockerfiles#4]
Thank you for geminabox image!

Is it possible to limit access to the root path for anonymous users at all? The main goal is to make a private repository with no possibility to download gems without password specified in Gemfile.

**Comment by yuri-karpovich** [comment]
I found a solution. Sorry.

The solution:
Add following lines to `config.ru`:

``` ruby
Geminabox::Server.before do
      protected! if request.get?
end if ENV['PRIVATE'].to_s == 'true'

```

**Comment by ahmet2mir** [comment]
Thanks @yuri-karpovich 

Maybe you can directly check "if ENV['PRIVATE'].to_s == 'true'" after if request.delete? (not tested)

```
Geminabox::Server.before do
    protected! if request.delete? || if ENV['PRIVATE'].to_s == 'true'?
end
```

And replace "No pushing or deleting without auth.\n" with a more proper message like yours "You have not access to this resource.\n" 

Finally, PR are welcome :)
